/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p77.reto5.Vista;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;



import utp.misiontic2022.c2.p77.reto5.Controlador.ControladorRequerimientos;
import utp.misiontic2022.c2.p77.reto5.Modelo.vo.Requerimiento_1;
import utp.misiontic2022.c2.p77.reto5.Modelo.vo.Requerimiento_2;
import utp.misiontic2022.c2.p77.reto5.Modelo.vo.Requerimiento_3;
/**
 *
 * @author cbecerra
 */
public class VistaMenuReq extends javax.swing.JFrame {
    /**
     * Creates new form VistaMenuReq
     */
    private final ControladorRequerimientos controladorRequerimientos;
    private Req1TM req1TM;
    private Req2TM req2TM;
    private Req3TM req3TM;
    

    public VistaMenuReq() {
        controladorRequerimientos = new ControladorRequerimientos();
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarRequerimiento1();
        MostrarRequerimiento2();
        MostrarRequerimiento3();
    }
 
    private void MostrarRequerimiento1() {
        try {
            //var requerimiento1;
            ArrayList<Requerimiento_1> requerimiento1 = controladorRequerimientos.consultarRequerimiento1();

            req1TM = new Req1TM(requerimiento1);
            jTable1.setModel(req1TM);

        
        } catch (SQLException e) {
        
        }
    }  
    private void MostrarRequerimiento2() {
        try {
            ArrayList<Requerimiento_2> requerimiento2 = controladorRequerimientos.consultarRequerimiento2();

            req2TM = new Req2TM(requerimiento2);
            jTable2.setModel(req2TM);

        } catch (SQLException e) {
        
        }
    } 
    private void MostrarRequerimiento3() {
        try {
            ArrayList<Requerimiento_3> requerimiento3 = controladorRequerimientos.consultarRequerimiento3();

            req3TM = new Req3TM(requerimiento3);
            jTable3.setModel(req3TM);

        
        } catch (SQLException e) {
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jFrame2 = new javax.swing.JFrame();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        tpPrincipal = new javax.swing.JTabbedPane();
        pRequerimiento1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spRequerimiento1 = new javax.swing.JSplitPane();
        pDesReq1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pTablaReq1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pRequerimiento2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        spRequerimiento2 = new javax.swing.JSplitPane();
        pDesReq2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pTablaReq2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pRequerimiento3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        mbOpciones = new javax.swing.JMenuBar();
        mOpciones = new javax.swing.JMenu();
        mRequisito1 = new javax.swing.JMenuItem();
        mRequisito2 = new javax.swing.JMenuItem();
        mRequisito3 = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenuItem();
        mAcercaDe = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Holding Construye - Requerimientos");
        setBounds(new java.awt.Rectangle(0, 0, 20, 20));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        setForeground(new java.awt.Color(0, 51, 153));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1, 1));
        setPreferredSize(new java.awt.Dimension(600, 500));

        tpPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpPrincipalMouseClicked(evt);
            }
        });

        pRequerimiento1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta Requerimiento 1");
        jLabel1.setToolTipText("");
        pRequerimiento1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        spRequerimiento1.setDividerLocation(45);
        spRequerimiento1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        spRequerimiento1.setEnabled(false);

        pDesReq1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Líderes constructora Edificios y Edificios,");

        javax.swing.GroupLayout pDesReq1Layout = new javax.swing.GroupLayout(pDesReq1);
        pDesReq1.setLayout(pDesReq1Layout);
        pDesReq1Layout.setHorizontalGroup(
            pDesReq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDesReq1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pDesReq1Layout.setVerticalGroup(
            pDesReq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDesReq1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spRequerimiento1.setTopComponent(pDesReq1);

        pTablaReq1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pTablaReq1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(221,211,211)));
        jScrollPane1.setViewportView(jTable1);

        pTablaReq1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        spRequerimiento1.setRightComponent(pTablaReq1);

        pRequerimiento1.add(spRequerimiento1, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("         Requerimiento 1         ", pRequerimiento1);

        pRequerimiento2.setEnabled(false);
        pRequerimiento2.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Consulta Requerimiento 2");
        jLabel3.setToolTipText("");
        pRequerimiento2.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        spRequerimiento2.setDividerLocation(45);
        spRequerimiento2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pDesReq2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Información de los proyectos: id de proyecto 19, 24, 37, 39, 58, 63.");

        javax.swing.GroupLayout pDesReq2Layout = new javax.swing.GroupLayout(pDesReq2);
        pDesReq2.setLayout(pDesReq2Layout);
        pDesReq2Layout.setHorizontalGroup(
            pDesReq2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDesReq2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pDesReq2Layout.setVerticalGroup(
            pDesReq2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDesReq2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        spRequerimiento2.setTopComponent(pDesReq2);

        pTablaReq2.setLayout(new java.awt.BorderLayout());

        jTable2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        pTablaReq2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        spRequerimiento2.setRightComponent(pTablaReq2);

        pRequerimiento2.add(spRequerimiento2, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("         Requerimiento 2         ", pRequerimiento2);

        pRequerimiento3.setEnabled(false);
        pRequerimiento3.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Consulta Requerimiento 3");
        jLabel5.setToolTipText("");
        pRequerimiento3.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(45);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Proyectos con costo superios a USD 85.000, ubicados en Salento y Armenia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel3);

        pRequerimiento3.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("         Requerimiento 3         ", pRequerimiento3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpPrincipal)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpPrincipal)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        mOpciones.setText("Opciones");

        mRequisito1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mRequisito1.setText("Requisito 1");
        mRequisito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRequisito1ActionPerformed(evt);
            }
        });
        mOpciones.add(mRequisito1);

        mRequisito2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mRequisito2.setText("Requisito 2");
        mRequisito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRequisito2ActionPerformed(evt);
            }
        });
        mOpciones.add(mRequisito2);

        mRequisito3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mRequisito3.setText("Requisito 3");
        mRequisito3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRequisito3ActionPerformed(evt);
            }
        });
        mOpciones.add(mRequisito3);

        mSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mOpciones.add(mSalir);

        mbOpciones.add(mOpciones);

        mAcercaDe.setText("Acerca de");
        mAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAcercaDeActionPerformed(evt);
            }
        });
        mbOpciones.add(mAcercaDe);

        setJMenuBar(mbOpciones);

        pack();
    }// </editor-fold>                        

    private void mRequisito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRequisito1ActionPerformed
        tpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_mRequisito1ActionPerformed

    private void mRequisito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRequisito3ActionPerformed
        tpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_mRequisito3ActionPerformed
    
public void abrirarchivo(String archivo){

     try {

            File objetofile = new File (archivo);
            Desktop.getDesktop().open(objetofile);

     }catch (IOException ex) {

            System.out.println(ex);

     }

}          

    private void mAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAcercaDeActionPerformed
        abrirarchivo("src/AcercaDe.txt");
    }//GEN-LAST:event_mAcercaDeActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        if (JOptionPane.showConfirmDialog(this,"¿Esta seguro de cerrar la aplicación?",
                getTitle(),JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
                dispose();
        }
    }//GEN-LAST:event_mSalirActionPerformed

    private void mRequisito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRequisito2ActionPerformed
        tpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_mRequisito2ActionPerformed

    private void tpPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpPrincipalMouseClicked

    }//GEN-LAST:event_tpPrincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuReq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JMenu mAcercaDe;
    private javax.swing.JMenu mOpciones;
    private javax.swing.JMenuItem mRequisito1;
    private javax.swing.JMenuItem mRequisito2;
    private javax.swing.JMenuItem mRequisito3;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuBar mbOpciones;
    private javax.swing.JPanel pDesReq1;
    private javax.swing.JPanel pDesReq2;
    private javax.swing.JPanel pRequerimiento1;
    private javax.swing.JPanel pRequerimiento2;
    private javax.swing.JPanel pRequerimiento3;
    private javax.swing.JPanel pTablaReq1;
    private javax.swing.JPanel pTablaReq2;
    private javax.swing.JSplitPane spRequerimiento1;
    private javax.swing.JSplitPane spRequerimiento2;
    private javax.swing.JTabbedPane tpPrincipal;
    // End of variables declaration//GEN-END:variables

}

